### ISSUE TITLE
packaging for windows

### ISSUE THREAD

**Issue by fdch** [danomatika/joyosc#7]
Ok, so I realized I could add the `DESTDIR` flag to `make install` and did that.

However, it created a `lib` subdirectory without the three dependencies that I manually added (liblo-7.dll, SDL2.dll, and libtinyxml2.dll). You can have a look [here](https://drive.google.com/file/d/1Bsom7Bf5WmQM5DITluo9hsuWiZNn9QZX/view?usp=sharing)

Trying to run from the bin, or from the root dir gave me an error for not finding the shared libs. So, I  moved all libs and `.exe`s to the same dir and got this:
```
$ ./joyosc.exe
.../Downloads/joyosc-installed/mingw64/joyosc.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
I am afraid I have no more info on this and wont be able to work on this until later this week. Hope any of this is helpful. Please, let me know if it isn't!

**Comment by danomatika** [comment]
The error print suggests you are still missing some DLLs, most probably libc which is included with MinGW. See what Dependency Walker says.

If you are also dependent on DLLS for tinyobject and loopback (two of my libraries), you can statically link them when building by configuring with:

    ./configure --disable-shared

Regarding the permissions settings in the manifest, I think the following is better in the XML:

~~~
 <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
~~~

I read "asInvoker" denotes regular user permissions and I don't think joyosc needs administrator access. It asked without the manifest since it had to guess what ptriveldges were needed as there wasn't a manifest.

**Comment by fdch** [comment]
Success!! I got it working on a different computer!

Your changes to mainfest worked perfectly well and I received absolutely **no warning from the antivirus**.

I remade the app with `./configure --disable-shared`

Running `depends.exe joyosc` showed the following libraries, which were all located in `msys2/mingw64/bin`:

- libgcc_s_seh-1.dll
-  liblo-7.dll
- libstdc++-6.dll
- libtinyxml2.dll
- libwinpthread-1.dll
- SDL2.dll

So, I copied all of them into the `bin` of the newly installed after `make install DESTDIR="joyosc-installed2"`, together with the mainfests, and voila! 

`joyosc.exe` is running and `joyosc-example.pd` is getting all the game controller events coming in from the PS4 controller.

CONGRATS AND THANKS!!!!!!

[here](https://drive.google.com/open?id=1KIwVCsrpgUXtTs8pgaCEaQUPtEIQkTr6)'s the package if you want to check it out.

**Comment by fdch** [comment]
I'll close this for now, but I am still trying to figure out how to make a simple `.bat` file that can run joyosc from a msys terminal. If anything, I could make another issue for that.

**Comment by danomatika** [comment]
Cool. We can probably wrap up those steps into a `make` rule as with Pd's `make app`.

If you want to try the same for macOS:

* `otool -L` will print the library dependencies of a program, ie. `otool -L joyosc`
* you can try copying the required dylibs into a hidden `.libs` directory in the same dir as joyosc & lsjs
* uninstall a lib dependency with homebrew before testing on the same machine, otherwise test on another machine

**Comment by danomatika** [comment]
Also, you want to use a `.bat` (aka DOS batch file) as it will work natively with the Windows CMD.exe prompt. You can also run any command line program in CMD. Either way, whoever will use your package will not need Msys.

**Comment by fdch** [comment]
I have tried running joyosc from the command line with no luck. It only runs from msys

fdch.github.io
